# Generated by Django 5.2 on 2025-05-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_filemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
